# Generated by Django 5.2.6 on 2025-10-07 18:23

from django.db import migrations


def rename_spices_to_powdered(apps, schema_editor):
    Category = apps.get_model('catalog', 'Category')
    try:
        cat = Category.objects.get(slug__iexact='spices')
        cat.name = 'Powdered'
        cat.slug = 'powdered'
        cat.save(update_fields=['name', 'slug'])
    except Category.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_image'),
    ]

    operations = [
        migrations.RunPython(rename_spices_to_powdered, migrations.RunPython.noop)
    ]
